### PR TITLE
Add my Python API client library to the integrations page

### PR DESCRIPTION
**Pull request by jdelic**
[aptly-api-client](https://github.com/gopythongo/aptly-api-client/) is a pythonic low-level abstraction over the aptly API.

### CODE REVIEW

**Review by smira — APPROVED** [review]
thank you!

**Comment by smira** [comment]
@jdelic actually master repo is https://github.com/aptly-dev/aptly-dev.github.io

 this is my personal fork, would you mind re-submitting your PR to aptly-dev? 

thanks!

**Comment by jdelic** [comment]
> this is my personal fork, would you mind re-submitting your PR to aptly-dev?

oops. No, not at all. 👍

**Comment by jdelic** [comment]
New PR is at https://github.com/aptly-dev/aptly-dev.github.io/pull/45

I still don't know how I ended up at a repo clearly marked as a fork... apologies.

**Comment by smira** [comment]
Thanks!

**Pull request closed without merging**
